//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCluster) DeepCopyInto(out *ContainerCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCluster.
func (in *ContainerCluster) DeepCopy() *ContainerCluster {
	if in == nil {
		return nil
	}
	out := new(ContainerCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterAcceleratorConfig) DeepCopyInto(out *ContainerClusterAcceleratorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterAcceleratorConfig.
func (in *ContainerClusterAcceleratorConfig) DeepCopy() *ContainerClusterAcceleratorConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterAcceleratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterAddonsConfig) DeepCopyInto(out *ContainerClusterAddonsConfig) {
	*out = *in
	if in.HttpLoadBalancing != nil {
		in, out := &in.HttpLoadBalancing, &out.HttpLoadBalancing
		*out = new(ContainerClusterHttpLoadBalancing)
		**out = **in
	}
	if in.HorizontalPodAutoscaling != nil {
		in, out := &in.HorizontalPodAutoscaling, &out.HorizontalPodAutoscaling
		*out = new(ContainerClusterHorizontalPodAutoscaling)
		**out = **in
	}
	if in.NetworkPolicyConfig != nil {
		in, out := &in.NetworkPolicyConfig, &out.NetworkPolicyConfig
		*out = new(ContainerClusterNetworkPolicyConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterAddonsConfig.
func (in *ContainerClusterAddonsConfig) DeepCopy() *ContainerClusterAddonsConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterAddonsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterClientCertificateConfig) DeepCopyInto(out *ContainerClusterClientCertificateConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterClientCertificateConfig.
func (in *ContainerClusterClientCertificateConfig) DeepCopy() *ContainerClusterClientCertificateConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterClientCertificateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterHorizontalPodAutoscaling) DeepCopyInto(out *ContainerClusterHorizontalPodAutoscaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterHorizontalPodAutoscaling.
func (in *ContainerClusterHorizontalPodAutoscaling) DeepCopy() *ContainerClusterHorizontalPodAutoscaling {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterHorizontalPodAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterHttpLoadBalancing) DeepCopyInto(out *ContainerClusterHttpLoadBalancing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterHttpLoadBalancing.
func (in *ContainerClusterHttpLoadBalancing) DeepCopy() *ContainerClusterHttpLoadBalancing {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterHttpLoadBalancing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterList) DeepCopyInto(out *ContainerClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterList.
func (in *ContainerClusterList) DeepCopy() *ContainerClusterList {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterMasterAuth) DeepCopyInto(out *ContainerClusterMasterAuth) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.ClientCertificateConfig != nil {
		in, out := &in.ClientCertificateConfig, &out.ClientCertificateConfig
		*out = new(ContainerClusterClientCertificateConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterMasterAuth.
func (in *ContainerClusterMasterAuth) DeepCopy() *ContainerClusterMasterAuth {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterMasterAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterNetworkPolicyConfig) DeepCopyInto(out *ContainerClusterNetworkPolicyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterNetworkPolicyConfig.
func (in *ContainerClusterNetworkPolicyConfig) DeepCopy() *ContainerClusterNetworkPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterNetworkPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterNodeConfig) DeepCopyInto(out *ContainerClusterNodeConfig) {
	*out = *in
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.DiskSizeGb != nil {
		in, out := &in.DiskSizeGb, &out.DiskSizeGb
		*out = new(int32)
		**out = **in
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImageType != nil {
		in, out := &in.ImageType, &out.ImageType
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LocalSsdCount != nil {
		in, out := &in.LocalSsdCount, &out.LocalSsdCount
		*out = new(int32)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Preemptible != nil {
		in, out := &in.Preemptible, &out.Preemptible
		*out = new(bool)
		**out = **in
	}
	if in.Accelerators != nil {
		in, out := &in.Accelerators, &out.Accelerators
		*out = make([]ContainerClusterAcceleratorConfig, len(*in))
		copy(*out, *in)
	}
	if in.DiskType != nil {
		in, out := &in.DiskType, &out.DiskType
		*out = new(string)
		**out = **in
	}
	if in.MinCpuPlatform != nil {
		in, out := &in.MinCpuPlatform, &out.MinCpuPlatform
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterNodeConfig.
func (in *ContainerClusterNodeConfig) DeepCopy() *ContainerClusterNodeConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterNodePools) DeepCopyInto(out *ContainerClusterNodePools) {
	*out = *in
	if in.InitialNodeCount != nil {
		in, out := &in.InitialNodeCount, &out.InitialNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ContainerClusterNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterNodePools.
func (in *ContainerClusterNodePools) DeepCopy() *ContainerClusterNodePools {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterNodePools)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterObservedState) DeepCopyInto(out *ContainerClusterObservedState) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.CurrentMasterVersion != nil {
		in, out := &in.CurrentMasterVersion, &out.CurrentMasterVersion
		*out = new(string)
		**out = **in
	}
	if in.CurrentNodeVersion != nil {
		in, out := &in.CurrentNodeVersion, &out.CurrentNodeVersion
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
	if in.NodeIpv4CidrSize != nil {
		in, out := &in.NodeIpv4CidrSize, &out.NodeIpv4CidrSize
		*out = new(int32)
		**out = **in
	}
	if in.ServicesIpv4Cidr != nil {
		in, out := &in.ServicesIpv4Cidr, &out.ServicesIpv4Cidr
		*out = new(string)
		**out = **in
	}
	if in.DefaultMaxPodsPerNode != nil {
		in, out := &in.DefaultMaxPodsPerNode, &out.DefaultMaxPodsPerNode
		*out = new(int32)
		**out = **in
	}
	if in.ExpireTime != nil {
		in, out := &in.ExpireTime, &out.ExpireTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterObservedState.
func (in *ContainerClusterObservedState) DeepCopy() *ContainerClusterObservedState {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterRef) DeepCopyInto(out *ContainerClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterRef.
func (in *ContainerClusterRef) DeepCopy() *ContainerClusterRef {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterSpec) DeepCopyInto(out *ContainerClusterSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(refsv1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.InitialNodeCount != nil {
		in, out := &in.InitialNodeCount, &out.InitialNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.MasterAuth != nil {
		in, out := &in.MasterAuth, &out.MasterAuth
		*out = new(ContainerClusterMasterAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.LoggingService != nil {
		in, out := &in.LoggingService, &out.LoggingService
		*out = new(string)
		**out = **in
	}
	if in.MonitoringService != nil {
		in, out := &in.MonitoringService, &out.MonitoringService
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.NetworkRef != nil {
		in, out := &in.NetworkRef, &out.NetworkRef
		*out = new(refsv1beta1.ComputeNetworkRef)
		**out = **in
	}
	if in.ClusterIpv4Cidr != nil {
		in, out := &in.ClusterIpv4Cidr, &out.ClusterIpv4Cidr
		*out = new(string)
		**out = **in
	}
	if in.AddonsConfig != nil {
		in, out := &in.AddonsConfig, &out.AddonsConfig
		*out = new(ContainerClusterAddonsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnetwork != nil {
		in, out := &in.Subnetwork, &out.Subnetwork
		*out = new(string)
		**out = **in
	}
	if in.SubnetworkRef != nil {
		in, out := &in.SubnetworkRef, &out.SubnetworkRef
		*out = new(refsv1beta1.ComputeSubnetworkRef)
		**out = **in
	}
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]ContainerClusterNodePools, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterSpec.
func (in *ContainerClusterSpec) DeepCopy() *ContainerClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterStatus) DeepCopyInto(out *ContainerClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(ContainerClusterObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterStatus.
func (in *ContainerClusterStatus) DeepCopy() *ContainerClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterStatus)
	in.DeepCopyInto(out)
	return out
}
