apiVersion: v1
data:
  cnrm.controller: gcr.io/gke-release/cnrm/controller:4fd3fd6
  cnrm.deletiondefender: gcr.io/gke-release/cnrm/deletiondefender:4fd3fd6
  cnrm.recorder: gcr.io/gke-release/cnrm/recorder:4fd3fd6
  cnrm.unmanageddetector: gcr.io/gke-release/cnrm/unmanageddetector:4fd3fd6
  cnrm.webhook: gcr.io/gke-release/cnrm/webhook:4fd3fd6
  prom-to-sd: gcr.io/gke-release-staging/prometheus-to-sd:v0.12.1-gke.1
kind: ConfigMap
metadata:
  annotations:
    components.gke.io/image-map: Images deployed by operator
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    cnrm.cloud.google.com/operator-system: "true"
  name: config-images
  namespace: configconnector-operator-system
